version: "3.4"

services:
  backend:
    build:
      context: .
    volumes:
      - .:/code/
    working_dir: /code
    command: ["python", "manage.py", "runserver", "0.0.0.0:5500"]
    ports:
      - "5500:5500"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:11.16-alpine
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tv_and_film
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  db-data:
    driver: local