[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
preview = true
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
^/(
    \.git
  | \.idea
  | \.pytest_cache
  | \.venv
  | venv
  | __pycache__
  | ci-scripts
  | \.coverage
  | old
  | build
  | dist
)
'''

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
