"""
Django settings for tv_and_film_buff project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import (
    AutoConfig,
    Config,
    RepositoryEnv,
)
from tv_and_film_buffAPI.config.fallbacks import SettingsFallbacks

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

settings_location = os.getenv("SETTINGS_LOCATION")
if settings_location is not None:
    config = Config(RepositoryEnv(settings_location))
else:
    config = AutoConfig()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "test"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    "tv_and_film_buffAPI.apps.WebservicesConfig",
    "corsheaders",
    "django_filters",
    "django_extensions",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = "tv_and_film_buffAPI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tv_and_film_buffAPI.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASE_ENGINE = config(
    "DATABASE_ENGINE", default="django.db.backends.postgresql_psycopg2"
)
DATABASE_HOST = config("DATABASE_HOST", default="localhost")
DATABASE_NAME = config("DATABASE_NAME", default=SettingsFallbacks.DATABASE_NAME.value)
DATABASE_PASSWORD = config(
    "DATABASE_PASSWORD", default=SettingsFallbacks.DATABASE_PASSWORD.value
)
DATABASE_USER = config("DATABASE_USER", default=SettingsFallbacks.DATABASE_USER.value)
DATABASE_PORT = config("DATABASE_PORT", default=5432)
DATABASE_SSL = config("DATABASE_SSL", default=False, cast=bool)

DATABASE_OPTIONS = {}
if DATABASE_SSL:
    DATABASE_OPTIONS["sslmode"] = "require"


DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE,
        "HOST": DATABASE_HOST,
        "NAME": DATABASE_NAME,
        "PASSWORD": DATABASE_PASSWORD,
        "USER": DATABASE_USER,
        "PORT": DATABASE_PORT,
        "OPTIONS": DATABASE_OPTIONS,
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
