# Generated by Django 4.0.4 on 2022-04-26 21:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_seasons', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField(default=1)),
                ('season_number', models.IntegerField(default=1)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Drama', 'Drama')], default='Action', max_length=22), size=None)),
                ('language', models.CharField(choices=[('English', 'English'), ('Greek', 'Greek'), ('Italian', 'Italian')], max_length=30)),
                ('imdbRating', models.CharField(max_length=10)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tv_and_film_buffAPI.series')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
