# Generated by Django 4.1.1 on 2022-10-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv_and_film_buffAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="series",
            old_name="seriesID",
            new_name="series_id",
        ),
    ]
