name: Testing

on:
  push:
env:
  DJANGO_SETTINGS_MODULE: tv_and_film_buffAPI.config.settings
  JEST_JUNIT_OUTPUT_FILE: /home/runner/work/tv-and-film-buff/tv-and-film-buff/unit-test-results.xml
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Unit-Tests:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.11]
        include:
          - DB: postgres
            DATABASE_USER: runner
            DATABASE_PASSWORD: ""
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        env:
          DB: ${{ matrix.DB }}
          DB_USER: ${{ matrix.DATABASE_USER }}
          DB_PASSWORD: ${{ matrix.DATABASE_PASSWORD }}
        run: pytest --junitxml=unit-test-results.xml
      - name: Check xml file for test results is there
        run: pwd && ls
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit-Tests-Report
          junit_files: "/home/runner/work/tv-and-film-buff/tv-and-film-buff/*.xml"
