name: call_testing_linting_with_db

on:
  push:
  workflow_dispatch:


jobs:
  call-reusable-testing-linting:
    uses: polyccon/github-action-reusable-workflows/.github/workflows/reusable-python-testing-linting-with-db.yml@main
    with:
      DJANGO_SETTINGS_MODULE: tv_and_film_buffAPI.config.settings
      directories_to_test: tv_and_film_buffAPI/