name: Testing

on:
  push:
env:
  DJANGO_SETTINGS_MODULE: tv_and_film_buffAPI.config.settings
  JEST_JUNIT_OUTPUT_FILE: /home/runner/work/tv-and-film-buff/tv-and-film-buff/unit-test-results.xml
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
  API_KEY: ${{ secrets.API_KEY }}
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    defaults:
      working_directory: "/"
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.11]
        include:
          - db: postgres
            db_port: 5432
            engine: postgres
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pwd && pytest --junitxml=unit-test-results.xml
      - name: Check xml file for test results is there
        run: pwd && ls
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit-Tests-Report
          junit_files: "/home/runner/work/tv-and-film-buff/tv-and-film-buff/*.xml"
