name: Testing

on:
  push:
env:
  DJANGO_SETTINGS_MODULE: tv_and_film_buffAPI.config.settings
  JEST_JUNIT_OUTPUT_FILE: results-dir/unit-test-results.xml
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_NAME: tv_and_film
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
  API_KEY: ${{ secrets.API_KEY }}
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.6, 3.7, 3.8]
        include:
          - db: postgres
            db_port: 5432
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./
    steps:
      - name: echo env var to see if secrets works
        run: echo ${{ secrets.DATABASE_PORT }}
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s ${{ secrets.DATABASE_USER }}
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Create results-dir
        run: mkdir -p results-dir
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest --junitxml=something.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit-Tests-Report
          junit_files: "results-dir/*.xml"
